### ISSUE TITLE
new 'preserve jenkinsfiles' logic breaks quickstarts

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-generator#60]
the new logic for imports unfortunately seems to break quickstarts now as they get created with the unusable RHOAR Jenkinsfiles instead which don't build/work on OSIO.

we should always replace the Jenkinsfiles when creating quickstarts as the RHOAR Jenkinsfiles are of negative value to OSIO (they don't work at all! :)

**Comment by jstrachan** [comment]
I guess we need some kinda flag to know if we are in the `quickstart` part of the wizard versus the`import` part to know whether or not to overwrite by default

**Comment by jstrachan** [comment]
the new 'overwrite Jenksinfiles' checkbox doesn't appear for quickstarts; but we should still enable it by default though!

**Comment by corinnekrych** [comment]
@jstrachan I've just tested it on PROD:

* here is the import flow:
![screenshot 2017-09-14 13 01 29-1](https://user-images.githubusercontent.com/1395710/30426630-015f18c6-994d-11e7-8fd2-40e225bef1e8.png)
which ask for overrride
![screenshot 2017-09-14 13 02 04](https://user-images.githubusercontent.com/1395710/30426646-13049452-994d-11e7-9df4-2a4d832d96af.png)
then finish is successful

* the quickstart flow with vertx:
![screenshot 2017-09-14 12 58 22](https://user-images.githubusercontent.com/1395710/30426666-29536cba-994d-11e7-88b3-52a4eab4c6cb.png)
no checkbox asked
![screenshot 2017-09-14 13 00 20](https://user-images.githubusercontent.com/1395710/30426676-2e49c610-994d-11e7-86be-d0477780d591.png)
successfully created.

Which flow is breaking? how to reproduce the issue?

**Comment by jstrachan** [comment]
what does the created Jenkinsfile look like? If its like [this one](https://github.com/jstrachan/cheese172/blob/master/Jenkinsfile) then its using the Jenkinsfile from the quickstart - not from fabric8/OSIO - which don't work on OSIO
