### ISSUE TITLE
Start using the new url for fetching github tokens

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-generator#70]
part of https://github.com/fabric8-services/fabric8-auth/issues/149

https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/keycloak/KeycloakEndpoint.java#L30

CC : @jstrachan @bartoszmajsak @corinnekrych

**Comment by jstrachan** [comment]
awesome thanks!  - ah thought it was a PR :) will try fix it on Friday if noone beats me to it

**Comment by alexeykazakov** [comment]
@jstrachan please take a look if I missed anything :)

- https://github.com/fabric8io/generator-backend/pull/69
- https://github.com/fabric8io/fabric8-generator/pull/71

**Comment by alexeykazakov** [comment]
Done. @sbose78 please close the issue.
